export { default as HomePage } from "./home-page/home-page"
export { default as HeroesPage } from "./heroes-pages/heroes-page"
export { default as HeroeDetailPage } from "./heroes-pages/heroes-detail-page"
export { default as GamesPage } from "./games-pages/game-page"
export { default as GamesDetailPage } from "./games-pages/game-detail-page"